#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Description of the Pravega Schema Registry APIs.

swagger: "2.0"
info:
  description: "REST APIs for Pravega Schema Registry."
  version: "0.0.1"
  title: Pravega Schema Registry APIs
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0"
basePath: "/v1"
tags:
- name: "Namespace"
  description: "Namespace related APIs"
- name: "Group"
  description: "Group related APIs"
- name: "Schema"
  description: "Schema related APIs"
- name: "Encoding"
  description: "Encoding related APIs"
schemes:
  - http
paths:
  /namespaces:
    get:
      tags:
      - "Namespace"
      operationId: listNamespaces
      description: List all available Namespaces in schema registry
      produces:
        - application/json
      responses:
        200:
          description: List of currently available Namespaces
          schema:
            $ref: "#/definitions/NamespacesList"
        500:
          description: Internal server error while fetching list of namespaces
    post:
      tags:
      - "Namespace"
      operationId: createNamespace
      description: Create a new Namespace
      consumes:
        - application/json
      parameters:
        - in: body
          name: CreateNamespaceRequest
          description: Create namespace
          required: true
          schema:
            type: object
            properties:
              namespaceName:
                type: string
      produces:
        - application/json
      responses:
        201:
          description: Successfully created the Namespace
        409:
          description: Namespace with the given name already exists
        500:
          description: Internal server error while creating a namespace
  /namespaces/{namespaceName}:
    parameters:
      - in: path
        name: namespaceName
        description: Namespace name
        required: true
        type: string
    delete:
      tags:
      - "Namespace"
      operationId: deleteNamespace
      description: Delete a namespace
      responses:
        204:
          description: Successfully deleted the namespace
        404:
          description: Namespace not found
        412:
          description: Cannot delete namespace since it has non-empty list of Groups
        500:
          description: Internal server error while deleting a namespace
  /namespaces/{namespaceName}/groups:
    parameters:
      - in: path
        name: namespaceName
        description: Namespace name
        required: true
        type: string
    get:
      tags:
      - "Group"
      operationId: listGroups
      description: List groups within the given namespace
      produces:
        - application/json
      responses:
        200:
          description: List of all groups under the given namespace namespace
          schema:
            $ref: "#/definitions/GroupsList"
        404:
          description: Namespace not found
        500:
          description: Internal server error while fetching the list of Groups for the given namespace
    post:
      tags:
      - "Group"
      operationId: createGroup
      description: Create a new Group
      consumes:
        - application/json
      parameters:
        - in: body
          name: CreateGroupRequest
          description: The Group configuration
          required: true
          schema:
            type: object
            properties:
              groupName:
                type: string
              schemaType:
                  $ref: "#/definitions/SchemaType"
              validationRules:
                  $ref: "#/definitions/SchemaValidationRules"
              enableEncoding:
                type: boolean
              groupByEventType:
                type: boolean
      responses:
        201:
          description: Successfully added group to the namespace
        404:
          description: Namespace not found
        409:
          description: Group with given name already exists
        500:
          description: Internal server error while creating a Group
  /namespaces/{namespaceName}/groups/{groupName}:
    parameters:
      - in: path
        name: namespaceName
        description: Namespace name
        required: true
        type: string
      - in: path
        name: GroupName
        description: Group name
        required: true
        type: string
    get:
      tags:
      - "Group"
      operationId: getGroupProperties
      description: Fetch the properties of an existing Group
      produces:
        - application/json
      responses:
        200:
          description: Found Group properties
          schema:
            $ref: "#/definitions/GroupProperties"
        404:
          description: Namespace or Group with given name not found
        500:
          description: Internal server error while fetching Group details
    put:
      tags:
      - "Group"
      operationId: updateSchemaValidationRules
      description: update schema validation rules of an existing Group
      consumes:
        - application/json
      parameters:
        - in: body
          name: UpdateValidationRulesPolicyRequest
          description: update group policy
          required: true
          schema:
            type: object
            properties:
              validationRules:
                  $ref: "#/definitions/SchemaValidationRules"
      responses:
        200:
          description: Updated schema validation policy
        404:
          description: Namespace or Group with given name not found
        409:
          description: Conflict while attempting to update policy. 
        500:
          description: Internal server error while fetching Group details
    delete:
      tags:
      - "Group"
      operationId: deleteGroup
      description: Delete a Group
      responses:
        204:
          description: Successfully deleted the Group
        404:
          description: Group not found
        500:
          description: Internal server error while deleting the Group
  /namespaces/{namespaceName}/groups/{groupName}/schemas:
    parameters:
      - in: path
        name: namespaceName
        description: Namespace name
        required: true
        type: string
      - in: path
        name: GroupName
        description: Group name
        required: true
        type: string
    get:
      tags:
      - "Schema"
      operationId: getGroupSchemas
      description: Fetch the properties of an existing Group
      produces:
        - application/json
      responses:
        200:
          description: Versioned history of schemas registered under the group
          schema:
            $ref: "#/definitions/SchemaEvolutionList"
        404:
          description: Namespace or Group with given name not found
        500:
          description: Internal server error while fetching Group details
    post:
      tags:
      - "Schema"
      operationId: addSchemaToGroupIfAbsent
      description: adds a new schema to the group
      consumes:
        - application/json
      parameters:
        - in: body
          name: AddSchemaToGroupRequest
          description: Add new schema to group
          required: true
          schema:
            type: object
            properties:
              schemaInfo:
                  $ref: "#/definitions/SchemaInfo"
              rules:
                  $ref: "#/definitions/SchemaValidationRules"
      produces:
        - application/json
      responses:
        201:
          description: Successfully added schema to the group
          schema:
            $ref: "#/definitions/VersionInfo"
        404:
          description: Namespace not found
        500:
          description: Internal server error while creating a Group
  /namespaces/{namespaceName}/groups/{groupName}/schemas/latest:
    parameters:
      - in: path
        name: namespaceName
        description: Namespace name
        required: true
        type: string
      - in: path
        name: GroupName
        description: Group name
        required: true
        type: string
    get:
      tags:
      - "Schema"
      operationId: getLatestGroupSchema
      description: Fetch the properties of an existing Group
      produces:
        - application/json
      responses:
        200:
          description: Found Group properties
          schema:
            $ref: "#/definitions/SchemaWithVersion"
        404:
          description: Namespace or Group with given name not found
        500:
          description: Internal server error while fetching Group details
  /namespaces/{namespaceName}/groups/{groupName}/schemas/validate:
    parameters:
      - in: path
        name: namespaceName
        description: Namespace name
        required: true
        type: string
      - in: path
        name: GroupName
        description: Group name
        required: true
        type: string
    get:
      tags:
      - "Schema"
      operationId: validate
      description: check if given schema is compatible with schemas in the registry for current policy setting. 
      consumes:
        - application/json
      parameters:
        - in: body
          name: ValidateRequest
          description: Checks if schema is valid with respect to supplied validation rules
          required: true
          schema:
            type: object
            properties:
              schemaInfo:
                  $ref: "#/definitions/SchemaInfo"
              validationRules:
                  $ref: "#/definitions/SchemaValidationRules"
      produces:
        - application/json
      responses:
        200:
          description: Schema is valid
        404:
          description: Namespace or Group with given name not found
        500:
          description: Internal server error while fetching Group details
  /namespaces/{namespaceName}/groups/{groupName}/schemas/version:
    parameters:
      - in: path
        name: namespaceName
        description: Namespace name
        required: true
        type: string
      - in: path
        name: GroupName
        description: Group name
        required: true
        type: string
    get:
      tags:
      - "Schema"
      operationId: getSchemaFromVersion
      description: Fetch the properties of an existing Group
      consumes:
        - application/json
      parameters:
        - in: body
          name: GetSchemaFromVersionRequest
          description: Get schema corresponding to the version
          required: true
          schema:
            type: object
            properties:
              versionInfo:
                  $ref: "#/definitions/VersionInfo"
      produces:
        - application/json
      responses:
        200:
          description: Schema corresponding to the version
          schema:
            $ref: "#/definitions/SchemaInfo"
        404:
          description: Namespace or Group with given name not found
        500:
          description: Internal server error while fetching Group details
  /namespaces/{namespaceName}/groups/{groupName}/subgroups/{subgroupName}/schemas:
    parameters:
      - in: path
        name: namespaceName
        description: Namespace name
        required: true
        type: string
      - in: path
        name: GroupName
        description: Group name
        required: true
        type: string
      - in: path
        name: SubgroupName
        description: Subgroup name
        required: true
        type: string
    get:
      tags:
      - "Schema"
      operationId: getSubGroupSchemas
      description: Fetch all schemas registered under a sub Group
      produces:
        - application/json
      responses:
        200:
          description: Versioned history of schemas registered under the group
          schema:
            $ref: "#/definitions/SchemaEvolutionList"
        404:
          description: Namespace or Group with given name not found
        500:
          description: Internal server error while fetching Group details
  /namespaces/{namespaceName}/groups/{groupName}/subgroups/{subgroupName}/schemas/latest:
    parameters:
      - in: path
        name: namespaceName
        description: Namespace name
        required: true
        type: string
      - in: path
        name: GroupName
        description: Group name
        required: true
        type: string
      - in: path
        name: SubgroupName
        description: Subgroup name
        required: true
        type: string
    get:
      tags:
      - "Schema"
      operationId: getLatestSubgroupSchema
      description: Fetch the properties of an existing Group
      produces:
        - application/json
      responses:
        200:
          description: Found latest schema in subgroup
          schema:
            $ref: "#/definitions/SchemaWithVersion"
        404:
          description: Namespace or Group with given name not found
        500:
          description: Internal server error while fetching Group details
  /namespaces/{namespaceName}/groups/{groupName}/encodings:
    parameters:
      - in: path
        name: namespaceName
        description: Namespace name
        required: true
        type: string
      - in: path
        name: GroupName
        description: Group name
        required: true
        type: string
    put:
      tags:
      - "Encoding"
      operationId: getOrGenerateEncodingId
      description: Fetch the properties of an existing Group
      consumes:
        - application/json
      parameters:
        - in: body
          name: GetEncodingIdRequest
          description: Get schema corresponding to the version
          required: true
          schema:
            type: object
            properties:
              subgroupName: 
                type: string
              versionInfo:
                  $ref: "#/definitions/VersionInfo"
              compressionType:
                  $ref: "#/definitions/CompressionType"
      produces:
        - application/json
      responses:
        200:
          description: Found Encoding
          schema:
            $ref: "#/definitions/EncodingId"
        404:
          description: Namespace or Group or encoding id with given name not found
        500:
          description: Internal server error while fetching Group details
  /namespaces/{namespaceName}/groups/{groupName}/encodings/{encodingId}:
    parameters:
      - in: path
        name: namespaceName
        description: Namespace name
        required: true
        type: string
      - in: path
        name: groupName
        description: Group name
        required: true
        type: string
      - in: path
        name: encodingId
        description: Encoding id that identifies a unique combination of encoding and compression
        required: true
        type: integer
        format: int32
    get:
      tags:
      - "Encoding"
      operationId: getEncodingInfo
      description: Fetch the properties of an existing Group
      produces:
        - application/json
      responses:
        200:
          description: Found Encoding
          schema:
            $ref: "#/definitions/EncodingInfo"
        404:
          description: Namespace or Group or encoding id with given name not found
        500:
          description: Internal server error while fetching Group details
  /namespaces/{namespaceName}/groups/{groupName}/compressions:
    parameters:
      - in: path
        name: namespaceName
        description: Namespace name
        required: true
        type: string
      - in: path
        name: GroupName
        description: Group name
        required: true
        type: string
    get:
      tags:
      - "Encoding"
      operationId: getCompressionsList
      description: Fetch the properties of an existing Group
      produces:
        - application/json
      responses:
        200:
          description: Found Compressions
          schema:
            $ref: "#/definitions/CompressionsList"
        404:
          description: Namespace or Group or encoding id with given name not found
        500:
          description: Internal server error while fetching Group details
definitions:
  NamespaceProperty:
    type: object
    properties:
      namespaceName:
        type: string
  NamespacesList:
    type: object
    properties:
      namespaces:
        type: array
        items:
          $ref: "#/definitions/NamespaceProperty"
  GroupsList:
    type: object
    properties:
      groups:
        type: array
        items:
          $ref: "#/definitions/GroupProperties"
  GroupProperties:
    type: object
    properties:
      groupName:
        type: string
      schemaValidationRules:
          $ref: "#/definitions/SchemaValidationRules"
      schemaType:
          $ref: "#/definitions/SchemaType"
      subgroupBySchemaName:
          type: boolean
      enableEncoding:
          type: boolean
  SchemaType:
    type: object
    properties:
      schemaType:
        type: string
        enum: 
          - None
          - Avro
          - Protobuf
          - Json
          - Custom
      customTypeName:
        type: string  
  SchemaInfo:
    type: object
    properties:
      schemaName:
        type: string
      schemaType:
          $ref: "#/definitions/SchemaType"
      schemaData:
        type: string
        format: binary
      properties:
        type: object
        additionalProperties:
          type: string
          minLength: 0
          maxLength: 40
  VersionInfo:
    type: object
    properties:
      schemaName:
        type: string
      version:
        type: integer
        format: int32
  SchemaWithVersion:
    type: object
    properties:
      schemaInfo:
        $ref: "#/definitions/SchemaInfo"
      version:
        $ref: "#/definitions/VersionInfo"
  SchemaEvolution:
    type: object
    properties:
      schemaInfo:
        $ref: "#/definitions/SchemaInfo"
      version:
        $ref: "#/definitions/VersionInfo"
      validationRules:
        $ref: "#/definitions/SchemaValidationRules"
  SchemaEvolutionList:
    type: object
    properties:
      schemas:
        type: array
        items:
          $ref: "#/definitions/SchemaEvolution"        
  CompressionType:
    type: object
    properties:
      compressionType:
        type: string
        enum:
          - None
          - Snappy
          - Gzip
          - Custom
      customTypeName:
        type: string
  EncodingId:
    type: object
    properties:
      encodingId:
        type: integer
        format: int32
  EncodingInfo:
    type: object
    properties:
      schemaInfo:
          $ref: "#/definitions/SchemaInfo"        
      versionInfo:
          $ref: "#/definitions/VersionInfo"        
      compressionType:
          $ref: "#/definitions/CompressionType"
  Compatibility:
    type: object
    properties:
      policy:
        type: string
        enum:
          - AllowAny
          - DisallowAll
          - Backward
          - Forward
          - ForwardTransitive
          - BackwardTransitive
          - BackwardTill
          - ForwardTill
          - BackwardAndForwardTill
          - Full
          - FullTransitive
      backwardTill:
        $ref: "#/definitions/VersionInfo"        
      forwardTill:
        $ref: "#/definitions/VersionInfo"        
  SchemaValidationRules:
    type: object
    properties:
       compatibility:
        $ref: "#/definitions/Compatibility"        
  CompressionsList:
    type: object
    properties:
       compressionTypes:
        type: array
        items:
          $ref: "#/definitions/CompressionType"
