apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "schema-registry.fullname" . }}
  labels:
    app: {{ include "schema-registry.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "schema-registry.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "schema-registry.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "schema-registry.configmap" . }}
          ports:
            - name: rest
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 2
            httpGet:
              path: /ping
              port: rest
          {{- if or .Values.authentication.enabled .Values.tls.enabled }}
          volumeMounts:
          {{- if .Values.authentication.enabled }}
          - name: {{ include "auth-volume.name" . }}
            mountPath: {{ include "auth-volume.path" . }}
            readOnly: true
          {{- end }}
          {{- if .Values.tls.enabled }}
          - name: {{ include "tls-volume.name" . }}
            mountPath: {{ include "tls-volume.path" . }}
            readOnly: true
          {{- end }}
          {{- end }}
      {{- if or .Values.authentication.enabled .Values.tls.enabled }}
      volumes:
      {{- if .Values.authentication.enabled }}
      - name: {{ include "auth-volume.name" . }}
        secret:
          secretName: {{ .Values.authentication.passwordAuthSecret }}
      {{- end }}
      {{- if .Values.tls.enabled }}
      - name: {{ include "tls-volume.name" . }}
        secret:
          secretName: {{ .Values.tls.secret }}
      {{- end }}
      {{- end }}
